# Generated by Django 5.1.3 on 2024-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('video_name', models.CharField(max_length=250)),
                ('srt', models.FileField(upload_to='srt')),
                ('data', models.JSONField()),
            ],
        ),
    ]
